### ISSUE TITLE
css properties?

### ISSUE THREAD

**Issue by jmsunseri** [benflap/tabler-icons-svelte#5]
is there any way that we could build this so that it will also work with css properties?  I'm using Tailwind CSS and specifying colors and what not through props really doesn't fit well

See how this icon set works
https://github.com/AnxiousDarkly/svelte-icons

**Comment by benflap** [comment]
I changed the default color to `currentColor`. I’m fairly certain this will fix your issue.

**Comment by jmsunseri** [comment]
This worked for the color.  I had to switch to controlling the size to the props but that might have been a cleaner solution in the long run than css.

**Comment by benflap** [comment]
Yes, I believe controlling size through props is cleaner.
